version: '3.5'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy
    volumes:
      - .ssh:/root/.ssh:ro
      - ./ert_wiki:/app/ert_wiki

  redis:
    image: "redis:7-alpine"
    container_name: my_redis_server
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - default

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  default:
    driver: bridge

volumes:
  redis_data: