version: '3.5'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    network_mode: "host"  # Use host's network configuration
    restart: unless-stopped
